// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: meta.proto

package meta

import (
	"fmt"

	proto "github.com/golang/protobuf/proto"

	math "math"

	_ "github.com/gogo/protobuf/gogoproto"

	io "io"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlatForm int32

const (
	PlatForm_Unknown PlatForm = 0
	PlatForm_Back    PlatForm = 1
	PlatForm_Front   PlatForm = 2
	PlatForm_IOS     PlatForm = 3
	PlatForm_Android PlatForm = 4
	PlatForm_NewSys  PlatForm = 5
)

var PlatForm_name = map[int32]string{
	0: "PlatForm_Unknown",
	1: "PlatForm_Back",
	2: "PlatForm_Front",
	3: "PlatForm_IOS",
	4: "PlatForm_Android",
	5: "PlatForm_NewSys",
}
var PlatForm_value = map[string]int32{
	"PlatForm_Unknown": 0,
	"PlatForm_Back":    1,
	"PlatForm_Front":   2,
	"PlatForm_IOS":     3,
	"PlatForm_Android": 4,
	"PlatForm_NewSys":  5,
}

func (x PlatForm) String() string {
	return proto.EnumName(PlatForm_name, int32(x))
}
func (PlatForm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{0}
}

type Message int32

const (
	Message_Unknown Message = 0
	Message_Confirm Message = 1
	Message_Notice  Message = 2
)

var Message_name = map[int32]string{
	0: "Message_Unknown",
	1: "Message_Confirm",
	2: "Message_Notice",
}
var Message_value = map[string]int32{
	"Message_Unknown": 0,
	"Message_Confirm": 1,
	"Message_Notice":  2,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}
func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{1}
}

type Server int32

const (
	Server_Unknown Server = 0
	Server_Eay     Server = 1
	Server_Ali     Server = 2
)

var Server_name = map[int32]string{
	0: "Server_Unknown",
	1: "Server_Eay",
	2: "Server_Ali",
}
var Server_value = map[string]int32{
	"Server_Unknown": 0,
	"Server_Eay":     1,
	"Server_Ali":     2,
}

func (x Server) String() string {
	return proto.EnumName(Server_name, int32(x))
}
func (Server) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{2}
}

type Status int32

const (
	Status_Unknown Status = 0
	Status_Wait    Status = 1
	Status_Cancel  Status = 2
	Status_Final   Status = 3
	// 批量完成
	Status_LotFinal Status = 4
)

var Status_name = map[int32]string{
	0: "Status_Unknown",
	1: "Status_Wait",
	2: "Status_Cancel",
	3: "Status_Final",
	4: "Status_LotFinal",
}
var Status_value = map[string]int32{
	"Status_Unknown":  0,
	"Status_Wait":     1,
	"Status_Cancel":   2,
	"Status_Final":    3,
	"Status_LotFinal": 4,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{3}
}

// "platform":3,
// "platform_key":"message_test",
// "server":2,
// "content": "验证码885588，您正在进行身份验证，打死不要告诉别人哦！",
// "template": "SMS_130990029",
// "arguments":"{\"code\":885588}",
// "mobile": "18516051096",
// "send_time":"2018-07-30T07:30:00+08:00",
// "type": 2
// SmsProducer 接收短信消息
type SmsProducer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform             int32    `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformKey          string   `protobuf:"bytes,3,opt,name=platformKey,proto3" json:"platformKey,omitempty"`
	Server               int32    `protobuf:"varint,4,opt,name=server,proto3" json:"server,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Template             string   `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"`
	Arguments            string   `protobuf:"bytes,7,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Mobile               string   `protobuf:"bytes,8,opt,name=mobile,proto3" json:"mobile,omitempty"`
	SendTime             string   `protobuf:"bytes,9,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XUtcSendStamp        int64    `protobuf:"varint,10,opt,name=_utcSendStamp,json=UtcSendStamp,proto3" json:"_utcSendStamp,omitempty"`
	Type                 int32    `protobuf:"varint,11,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsProducer) Reset()         { *m = SmsProducer{} }
func (m *SmsProducer) String() string { return proto.CompactTextString(m) }
func (*SmsProducer) ProtoMessage()    {}
func (*SmsProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{0}
}
func (m *SmsProducer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SmsProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SmsProducer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SmsProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsProducer.Merge(dst, src)
}
func (m *SmsProducer) XXX_Size() int {
	return m.Size()
}
func (m *SmsProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsProducer.DiscardUnknown(m)
}

var xxx_messageInfo_SmsProducer proto.InternalMessageInfo

func (m *SmsProducer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SmsProducer) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *SmsProducer) GetPlatformKey() string {
	if m != nil {
		return m.PlatformKey
	}
	return ""
}

func (m *SmsProducer) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *SmsProducer) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *SmsProducer) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *SmsProducer) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *SmsProducer) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *SmsProducer) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *SmsProducer) GetXUtcSendStamp() int64 {
	if m != nil {
		return m.XUtcSendStamp
	}
	return 0
}

func (m *SmsProducer) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// "platform":3,
// "platform_key":"email_test",
// "server":2,
// "title":"测试邮件",
// "content": "好嗨哟，感觉人生已经到达了高潮",
// "template": "test.blade.php",
// "arguments":"{\"name\":\"乔治君\"}",
// "destination": "923143925@qq.com",
// "send_time":"2018-07-30T07:30:00+08:00",
// "type": 2
// EmailProducer 接收email信息
type EmailProducer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform             int32    `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformKey          string   `protobuf:"bytes,3,opt,name=platformKey,proto3" json:"platformKey,omitempty"`
	Server               int32    `protobuf:"varint,4,opt,name=server,proto3" json:"server,omitempty"`
	Title                string   `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Template             string   `protobuf:"bytes,7,opt,name=template,proto3" json:"template,omitempty"`
	Arguments            string   `protobuf:"bytes,8,opt,name=arguments,proto3" json:"arguments,omitempty"`
	Destination          string   `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	SendTime             string   `protobuf:"bytes,10,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XUtcSendStamp        int64    `protobuf:"varint,11,opt,name=_utcSendStamp,json=UtcSendStamp,proto3" json:"_utcSendStamp,omitempty"`
	Type                 int32    `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailProducer) Reset()         { *m = EmailProducer{} }
func (m *EmailProducer) String() string { return proto.CompactTextString(m) }
func (*EmailProducer) ProtoMessage()    {}
func (*EmailProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{1}
}
func (m *EmailProducer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EmailProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EmailProducer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *EmailProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailProducer.Merge(dst, src)
}
func (m *EmailProducer) XXX_Size() int {
	return m.Size()
}
func (m *EmailProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailProducer.DiscardUnknown(m)
}

var xxx_messageInfo_EmailProducer proto.InternalMessageInfo

func (m *EmailProducer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *EmailProducer) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *EmailProducer) GetPlatformKey() string {
	if m != nil {
		return m.PlatformKey
	}
	return ""
}

func (m *EmailProducer) GetServer() int32 {
	if m != nil {
		return m.Server
	}
	return 0
}

func (m *EmailProducer) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *EmailProducer) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *EmailProducer) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *EmailProducer) GetArguments() string {
	if m != nil {
		return m.Arguments
	}
	return ""
}

func (m *EmailProducer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *EmailProducer) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *EmailProducer) GetXUtcSendStamp() int64 {
	if m != nil {
		return m.XUtcSendStamp
	}
	return 0
}

func (m *EmailProducer) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

// "platform":3,
// "touser": "oAdVsv5nQ-qtBF0F5WGU-xPcrpGY",
// "template_id": "RlJfVX1SCBW2ncbIblbOE_8PaOUyoxBmr2MKnjzcY80",
// "url": "",
// "data":"{\"first\": {\"value\":\"亲爱的George家长，UU哥提示您：本次课程已经结束，本节课配有课后作业哦，作业信息如下：\",\"color\":\"#173177\"},\"keyword1\":{\"value\":\"Hello\",\"color\":\"#173177\"},\"keyword2\": {\"value\":\"World\",\"color\":\"#173177\"},\"remark\":{\"value\":\"请提醒小朋友前往学习记录完成课后作业，完成作业还会有额外奖励哦。。如有任何问题可微信对话框留言或拨打服务热线：4001636161\",\"color\":\"#173177\"}}",
// "send_time":"0",
// "type": 2
// WeChatProducer 接收微信消息
type WeChatProducer struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Platform             int32    `protobuf:"varint,2,opt,name=platform,proto3" json:"platform,omitempty"`
	Touser               string   `protobuf:"bytes,3,opt,name=touser,proto3" json:"touser,omitempty"`
	TemplateID           string   `protobuf:"bytes,4,opt,name=templateID,proto3" json:"templateID,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Data                 string   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	SendTime             string   `protobuf:"bytes,7,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	XUtcSendStamp        int64    `protobuf:"varint,8,opt,name=_utcSendStamp,json=UtcSendStamp,proto3" json:"_utcSendStamp,omitempty"`
	Type                 int32    `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WeChatProducer) Reset()         { *m = WeChatProducer{} }
func (m *WeChatProducer) String() string { return proto.CompactTextString(m) }
func (*WeChatProducer) ProtoMessage()    {}
func (*WeChatProducer) Descriptor() ([]byte, []int) {
	return fileDescriptor_meta_bf2c42e17a09c808, []int{2}
}
func (m *WeChatProducer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WeChatProducer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WeChatProducer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *WeChatProducer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeChatProducer.Merge(dst, src)
}
func (m *WeChatProducer) XXX_Size() int {
	return m.Size()
}
func (m *WeChatProducer) XXX_DiscardUnknown() {
	xxx_messageInfo_WeChatProducer.DiscardUnknown(m)
}

var xxx_messageInfo_WeChatProducer proto.InternalMessageInfo

func (m *WeChatProducer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WeChatProducer) GetPlatform() int32 {
	if m != nil {
		return m.Platform
	}
	return 0
}

func (m *WeChatProducer) GetTouser() string {
	if m != nil {
		return m.Touser
	}
	return ""
}

func (m *WeChatProducer) GetTemplateID() string {
	if m != nil {
		return m.TemplateID
	}
	return ""
}

func (m *WeChatProducer) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *WeChatProducer) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *WeChatProducer) GetSendTime() string {
	if m != nil {
		return m.SendTime
	}
	return ""
}

func (m *WeChatProducer) GetXUtcSendStamp() int64 {
	if m != nil {
		return m.XUtcSendStamp
	}
	return 0
}

func (m *WeChatProducer) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func init() {
	proto.RegisterType((*SmsProducer)(nil), "meta.SmsProducer")
	proto.RegisterType((*EmailProducer)(nil), "meta.EmailProducer")
	proto.RegisterType((*WeChatProducer)(nil), "meta.WeChatProducer")
	proto.RegisterEnum("meta.PlatForm", PlatForm_name, PlatForm_value)
	proto.RegisterEnum("meta.Message", Message_name, Message_value)
	proto.RegisterEnum("meta.Server", Server_name, Server_value)
	proto.RegisterEnum("meta.Status", Status_name, Status_value)
}
func (m *SmsProducer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SmsProducer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.Platform != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Platform))
	}
	if len(m.PlatformKey) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.PlatformKey)))
		i += copy(dAtA[i:], m.PlatformKey)
	}
	if m.Server != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Server))
	}
	if len(m.Content) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Content)))
		i += copy(dAtA[i:], m.Content)
	}
	if len(m.Template) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Template)))
		i += copy(dAtA[i:], m.Template)
	}
	if len(m.Arguments) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Arguments)))
		i += copy(dAtA[i:], m.Arguments)
	}
	if len(m.Mobile) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Mobile)))
		i += copy(dAtA[i:], m.Mobile)
	}
	if len(m.SendTime) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.SendTime)))
		i += copy(dAtA[i:], m.SendTime)
	}
	if m.XUtcSendStamp != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *EmailProducer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EmailProducer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.Platform != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Platform))
	}
	if len(m.PlatformKey) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.PlatformKey)))
		i += copy(dAtA[i:], m.PlatformKey)
	}
	if m.Server != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Server))
	}
	if len(m.Title) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Title)))
		i += copy(dAtA[i:], m.Title)
	}
	if len(m.Content) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Content)))
		i += copy(dAtA[i:], m.Content)
	}
	if len(m.Template) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Template)))
		i += copy(dAtA[i:], m.Template)
	}
	if len(m.Arguments) > 0 {
		dAtA[i] = 0x42
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Arguments)))
		i += copy(dAtA[i:], m.Arguments)
	}
	if len(m.Destination) > 0 {
		dAtA[i] = 0x4a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Destination)))
		i += copy(dAtA[i:], m.Destination)
	}
	if len(m.SendTime) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.SendTime)))
		i += copy(dAtA[i:], m.SendTime)
	}
	if m.XUtcSendStamp != 0 {
		dAtA[i] = 0x58
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		dAtA[i] = 0x60
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *WeChatProducer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WeChatProducer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.Platform != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Platform))
	}
	if len(m.Touser) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Touser)))
		i += copy(dAtA[i:], m.Touser)
	}
	if len(m.TemplateID) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.TemplateID)))
		i += copy(dAtA[i:], m.TemplateID)
	}
	if len(m.Url) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.SendTime) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintMeta(dAtA, i, uint64(len(m.SendTime)))
		i += copy(dAtA[i:], m.SendTime)
	}
	if m.XUtcSendStamp != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintMeta(dAtA, i, uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintMeta(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *SmsProducer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.Platform != 0 {
		n += 1 + sovMeta(uint64(m.Platform))
	}
	l = len(m.PlatformKey)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.Server != 0 {
		n += 1 + sovMeta(uint64(m.Server))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Template)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Arguments)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Mobile)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.SendTime)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.XUtcSendStamp != 0 {
		n += 1 + sovMeta(uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		n += 1 + sovMeta(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EmailProducer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.Platform != 0 {
		n += 1 + sovMeta(uint64(m.Platform))
	}
	l = len(m.PlatformKey)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.Server != 0 {
		n += 1 + sovMeta(uint64(m.Server))
	}
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Content)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Template)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Arguments)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.SendTime)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.XUtcSendStamp != 0 {
		n += 1 + sovMeta(uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		n += 1 + sovMeta(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *WeChatProducer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.Platform != 0 {
		n += 1 + sovMeta(uint64(m.Platform))
	}
	l = len(m.Touser)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.TemplateID)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	l = len(m.SendTime)
	if l > 0 {
		n += 1 + l + sovMeta(uint64(l))
	}
	if m.XUtcSendStamp != 0 {
		n += 1 + sovMeta(uint64(m.XUtcSendStamp))
	}
	if m.Type != 0 {
		n += 1 + sovMeta(uint64(m.Type))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMeta(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMeta(x uint64) (n int) {
	return sovMeta(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SmsProducer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SmsProducer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SmsProducer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Platform", wireType)
			}
			m.Platform = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Platform |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlatformKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			m.Server = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Server |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Template = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arguments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arguments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mobile", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mobile = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field XUtcSendStamp", wireType)
			}
			m.XUtcSendStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.XUtcSendStamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EmailProducer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EmailProducer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EmailProducer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Platform", wireType)
			}
			m.Platform = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Platform |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlatformKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlatformKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Server", wireType)
			}
			m.Server = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Server |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Content", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Content = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Template", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Template = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Arguments", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Arguments = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field XUtcSendStamp", wireType)
			}
			m.XUtcSendStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.XUtcSendStamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WeChatProducer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WeChatProducer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WeChatProducer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Platform", wireType)
			}
			m.Platform = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Platform |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Touser", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Touser = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TemplateID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TemplateID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SendTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMeta
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SendTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field XUtcSendStamp", wireType)
			}
			m.XUtcSendStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.XUtcSendStamp |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMeta(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMeta
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMeta(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMeta
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMeta
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMeta
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMeta
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMeta(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMeta = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMeta   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("meta.proto", fileDescriptor_meta_bf2c42e17a09c808) }

var fileDescriptor_meta_bf2c42e17a09c808 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xc1, 0x6e, 0x13, 0x3d,
	0x10, 0xc7, 0xeb, 0x4d, 0xb2, 0x49, 0x26, 0x6d, 0xea, 0xcf, 0x5f, 0x54, 0x59, 0x15, 0x8a, 0xa2,
	0x72, 0xa9, 0x72, 0x80, 0x03, 0x57, 0x2e, 0x6d, 0x69, 0x51, 0x05, 0x94, 0x2a, 0x4b, 0xd5, 0x63,
	0xe5, 0x66, 0xdd, 0x60, 0x75, 0xd7, 0x8e, 0xbc, 0x13, 0xaa, 0xdc, 0x79, 0x08, 0x1e, 0x84, 0x87,
	0xe0, 0xd8, 0x13, 0x67, 0x28, 0x0f, 0xc0, 0x2b, 0x20, 0x7b, 0x9d, 0x74, 0x8b, 0x44, 0x2b, 0x71,
	0xe0, 0xf6, 0x9f, 0x9f, 0x35, 0xb3, 0x33, 0x3f, 0x45, 0x01, 0xc8, 0x25, 0x8a, 0x27, 0x53, 0x6b,
	0xd0, 0xb0, 0xba, 0xcb, 0x9b, 0xbd, 0x89, 0x99, 0x18, 0x0f, 0x9e, 0xba, 0x54, 0xbe, 0x6d, 0x7d,
	0x8e, 0xa0, 0x93, 0xe4, 0xc5, 0xb1, 0x35, 0xe9, 0x6c, 0x2c, 0x2d, 0xeb, 0x42, 0xa4, 0x52, 0x4e,
	0x06, 0x64, 0xbb, 0x3d, 0x8a, 0x54, 0xca, 0x36, 0xa1, 0x35, 0xcd, 0x04, 0x5e, 0x18, 0x9b, 0xf3,
	0x68, 0x40, 0xb6, 0x1b, 0xa3, 0x65, 0xcd, 0x06, 0xd0, 0x59, 0xe4, 0x57, 0x72, 0xce, 0x6b, 0xbe,
	0xa9, 0x8a, 0xd8, 0x06, 0xc4, 0x85, 0xb4, 0x1f, 0xa4, 0xe5, 0x75, 0xdf, 0x1b, 0x2a, 0xc6, 0xa1,
	0x39, 0x36, 0x1a, 0xa5, 0x46, 0xde, 0xf0, 0x5d, 0x8b, 0xd2, 0x7d, 0x0f, 0x65, 0xee, 0x66, 0x48,
	0x1e, 0xfb, 0xa7, 0x65, 0xcd, 0x1e, 0x41, 0x5b, 0xd8, 0xc9, 0x2c, 0x97, 0x1a, 0x0b, 0xde, 0xf4,
	0x8f, 0xb7, 0xc0, 0x7d, 0x2b, 0x37, 0xe7, 0x2a, 0x93, 0xbc, 0xe5, 0x9f, 0x42, 0xe5, 0x26, 0x16,
	0x52, 0xa7, 0xef, 0x54, 0x2e, 0x79, 0xbb, 0x9c, 0xb8, 0xa8, 0xd9, 0x63, 0x58, 0x3b, 0x9b, 0xe1,
	0x38, 0x91, 0x3a, 0x4d, 0x50, 0xe4, 0x53, 0x0e, 0x03, 0xb2, 0x5d, 0x1b, 0xad, 0x9e, 0x54, 0x18,
	0x63, 0x50, 0xc7, 0xf9, 0x54, 0xf2, 0x8e, 0x3f, 0xc1, 0xe7, 0xad, 0xaf, 0x11, 0xac, 0xed, 0xe7,
	0x42, 0x65, 0xff, 0x58, 0x5c, 0x0f, 0x1a, 0xa8, 0x30, 0x93, 0x41, 0x5b, 0x59, 0x54, 0x75, 0xc6,
	0x7f, 0xd6, 0xd9, 0xbc, 0x4f, 0x67, 0xeb, 0x77, 0x9d, 0x03, 0xe8, 0xa4, 0xb2, 0x40, 0xa5, 0x05,
	0x2a, 0xa3, 0x83, 0xb9, 0x2a, 0xba, 0x23, 0x16, 0x1e, 0x12, 0xdb, 0xb9, 0x47, 0xec, 0x6a, 0x45,
	0xec, 0x4f, 0x02, 0xdd, 0x53, 0xb9, 0xf7, 0x5e, 0xe0, 0x5f, 0x99, 0xdd, 0x80, 0x18, 0xcd, 0xac,
	0x90, 0x36, 0x48, 0x0d, 0x15, 0xeb, 0x03, 0x2c, 0xee, 0x3e, 0x7c, 0xe1, 0x9d, 0xb6, 0x47, 0x15,
	0xc2, 0x28, 0xd4, 0x66, 0x36, 0x0b, 0x56, 0x5d, 0x74, 0xcb, 0xa5, 0x02, 0x45, 0x10, 0xea, 0xf3,
	0x9d, 0x8b, 0x9b, 0x0f, 0x5d, 0xdc, 0xba, 0xe7, 0xe2, 0xf6, 0xed, 0xc5, 0xc3, 0x8f, 0x04, 0x5a,
	0xc7, 0x99, 0xc0, 0x03, 0xb7, 0x7f, 0x0f, 0xe8, 0x22, 0x9f, 0x9d, 0xe8, 0x4b, 0x6d, 0xae, 0x34,
	0x5d, 0x61, 0xff, 0xc1, 0xda, 0x92, 0xee, 0x8a, 0xf1, 0x25, 0x25, 0x8c, 0x41, 0x77, 0x89, 0x0e,
	0xac, 0xd1, 0x48, 0x23, 0x46, 0x61, 0x75, 0xc9, 0x0e, 0xdf, 0x26, 0xb4, 0x76, 0x67, 0xdc, 0x8e,
	0x4e, 0xad, 0x51, 0x29, 0xad, 0xb3, 0xff, 0x61, 0x7d, 0x49, 0x8f, 0xe4, 0x55, 0x32, 0x2f, 0x68,
	0x63, 0xf8, 0x12, 0x9a, 0x6f, 0x64, 0x51, 0x88, 0x89, 0x74, 0xef, 0x21, 0x56, 0x76, 0xa8, 0xc0,
	0x3d, 0xa3, 0x2f, 0x94, 0xcd, 0xcb, 0x2d, 0x16, 0xf0, 0xc8, 0xa0, 0x1a, 0x4b, 0x1a, 0x0d, 0x9f,
	0x43, 0x9c, 0x94, 0x3f, 0x56, 0x06, 0xdd, 0x32, 0x55, 0xc6, 0x74, 0x01, 0x02, 0xdb, 0x17, 0x73,
	0x4a, 0x2a, 0xf5, 0x4e, 0xa6, 0x68, 0x34, 0x9c, 0x40, 0x9c, 0xa0, 0xc0, 0x59, 0xe1, 0xbb, 0x7d,
	0xaa, 0x74, 0xaf, 0x43, 0x27, 0xb0, 0x53, 0xa1, 0x90, 0x12, 0x67, 0x26, 0x80, 0x3d, 0xa1, 0xc7,
	0x32, 0x2b, 0x2d, 0x04, 0x74, 0xa0, 0xb4, 0xc8, 0x68, 0xcd, 0xad, 0x1e, 0xc8, 0x6b, 0x83, 0x25,
	0xac, 0xef, 0xf6, 0xae, 0xbf, 0xf7, 0x57, 0xbe, 0xdc, 0xf4, 0xc9, 0xf5, 0x4d, 0x9f, 0x7c, 0xbb,
	0xe9, 0x93, 0x4f, 0x3f, 0xfa, 0x2b, 0xe7, 0xb1, 0xff, 0x57, 0x7c, 0xf6, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x1a, 0x77, 0xa1, 0x5a, 0x3f, 0x05, 0x00, 0x00,
}
